/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FrameworksRouteImport } from './routes/frameworks'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResponsibleAiRouteImport } from './routes/responsible-ai'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as FeaturesSlugRouteImport } from './routes/features.$slug'
import { Route as FrameworksSlugRouteImport } from './routes/frameworks.$slug'
import { Route as SolutionsSlugRouteImport } from './routes/solutions.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameworksRoute = FrameworksRouteImport.update({
  id: '/frameworks',
  path: '/frameworks',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsibleAiRoute = ResponsibleAiRouteImport.update({
  id: '/responsible-ai',
  path: '/responsible-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesSlugRoute = FeaturesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FeaturesRoute,
} as any)
const FrameworksSlugRoute = FrameworksSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FrameworksRoute,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SolutionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRouteWithChildren
  '/frameworks': typeof FrameworksRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/responsible-ai': typeof ResponsibleAiRoute
  '/security': typeof SecurityRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/features/$slug': typeof FeaturesSlugRoute
  '/frameworks/$slug': typeof FrameworksSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRouteWithChildren
  '/frameworks': typeof FrameworksRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/responsible-ai': typeof ResponsibleAiRoute
  '/security': typeof SecurityRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/features/$slug': typeof FeaturesSlugRoute
  '/frameworks/$slug': typeof FrameworksSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/features': typeof FeaturesRouteWithChildren
  '/frameworks': typeof FrameworksRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/responsible-ai': typeof ResponsibleAiRoute
  '/security': typeof SecurityRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/features/$slug': typeof FeaturesSlugRoute
  '/frameworks/$slug': typeof FrameworksSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/features'
    | '/frameworks'
    | '/integrations'
    | '/platform'
    | '/pricing'
    | '/responsible-ai'
    | '/security'
    | '/solutions'
    | '/features/$slug'
    | '/frameworks/$slug'
    | '/solutions/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/features'
    | '/frameworks'
    | '/integrations'
    | '/platform'
    | '/pricing'
    | '/responsible-ai'
    | '/security'
    | '/solutions'
    | '/features/$slug'
    | '/frameworks/$slug'
    | '/solutions/$slug'
  id:
    | '__root__'
    | '/'
    | '/features'
    | '/frameworks'
    | '/integrations'
    | '/platform'
    | '/pricing'
    | '/responsible-ai'
    | '/security'
    | '/solutions'
    | '/features/$slug'
    | '/frameworks/$slug'
    | '/solutions/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeaturesRoute: typeof FeaturesRouteWithChildren
  FrameworksRoute: typeof FrameworksRouteWithChildren
  IntegrationsRoute: typeof IntegrationsRoute
  PlatformRoute: typeof PlatformRoute
  PricingRoute: typeof PricingRoute
  ResponsibleAiRoute: typeof ResponsibleAiRoute
  SecurityRoute: typeof SecurityRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frameworks': {
      id: '/frameworks'
      path: '/frameworks'
      fullPath: '/frameworks'
      preLoaderRoute: typeof FrameworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsible-ai': {
      id: '/responsible-ai'
      path: '/responsible-ai'
      fullPath: '/responsible-ai'
      preLoaderRoute: typeof ResponsibleAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/$slug': {
      id: '/features/$slug'
      path: '/$slug'
      fullPath: '/features/$slug'
      preLoaderRoute: typeof FeaturesSlugRouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/frameworks/$slug': {
      id: '/frameworks/$slug'
      path: '/$slug'
      fullPath: '/frameworks/$slug'
      preLoaderRoute: typeof FrameworksSlugRouteImport
      parentRoute: typeof FrameworksRoute
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof SolutionsRoute
    }
  }
}

interface FeaturesRouteChildren {
  FeaturesSlugRoute: typeof FeaturesSlugRoute
}

const FeaturesRouteChildren: FeaturesRouteChildren = {
  FeaturesSlugRoute: FeaturesSlugRoute,
}

const FeaturesRouteWithChildren = FeaturesRoute._addFileChildren(
  FeaturesRouteChildren,
)

interface FrameworksRouteChildren {
  FrameworksSlugRoute: typeof FrameworksSlugRoute
}

const FrameworksRouteChildren: FrameworksRouteChildren = {
  FrameworksSlugRoute: FrameworksSlugRoute,
}

const FrameworksRouteWithChildren = FrameworksRoute._addFileChildren(
  FrameworksRouteChildren,
)

interface SolutionsRouteChildren {
  SolutionsSlugRoute: typeof SolutionsSlugRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsSlugRoute: SolutionsSlugRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeaturesRoute: FeaturesRouteWithChildren,
  FrameworksRoute: FrameworksRouteWithChildren,
  IntegrationsRoute: IntegrationsRoute,
  PlatformRoute: PlatformRoute,
  PricingRoute: PricingRoute,
  ResponsibleAiRoute: ResponsibleAiRoute,
  SecurityRoute: SecurityRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
